In [4]:
import pandas as pd
# from IPython.display import FileLink  # just for downloading data from remote jupyter notebooks


## Loading the dataset

In [5]:
df = pd.read_csv('../data/nba2k-full.csv').set_index('full_name')
df.head()

rating jersey                  team position     b_day  \
full_name                                                                       
LeBron James               97    #23    Los Angeles Lakers        F  12/30/84   
Kawhi Leonard              97     #2  Los Angeles Clippers        F  06/29/91   
Giannis Antetokounmpo      96    #34       Milwaukee Bucks      F-G  12/06/94   
Kevin Durant               96     #7         Brooklyn Nets        F  09/29/88   
James Harden               96    #13       Houston Rockets        G  08/26/89   

                            height                weight     salary country  \
full_name                                                                     
LeBron James            6-9 / 2.06  250 lbs. / 113.4 kg.  $37436858     USA   
Kawhi Leonard           6-7 / 2.01  225 lbs. / 102.1 kg.  $32742000     USA   
Giannis Antetokounmpo  6-11 / 2.11  242 lbs. / 109.8 kg.  $25842697  Greece   
Kevin Durant           6-10 / 2.08  230 lbs. / 104.3 kg.  $37199000     USA   
James Harden            6-5 / 1.96   220 lbs. / 99.8 kg.  $38199000     USA   

                       draft_year  draft_round  draft_peak          college  \
full_name                                                                     
LeBron James                 2003            1           1              NaN   
Kawhi Leonard                2011            1          15  San Diego State   
Giannis Antetokounmpo        2013            1          15              NaN   
Kevin Durant                 2007            1           2            Texas   
James Harden                 2009            1           3    Arizona State   

                       version  
full_name                       
LeBron James           NBA2k20  
Kawhi Leonard          NBA2k20  
Giannis Antetokounmpo  NBA2k20  
Kevin Durant           NBA2k20  
James Harden           NBA2k20

## Convert the dataset into a dictionary

In [6]:
players_data = df.to_dict('index')
print(type(players_data))

<class 'dict'>


## Activities

### Activity 1: Access the value using key
Find the height of the player 'LeBron James' from the dictionary players_data and store it in a variable lebron_height.

In [7]:
lebron_height = players_data['LeBron James']['height']
lebron_height

'6-9 / 2.06'

### Activity 2: Add a new player to the player data dictionary

Add a new player to the dictionary players_data. The new player is Stephen Curry and his data is given below:

"""
{'jersey': 30,
 'team': 'Golden State Warriors',
 'position': 'PG',
 'rating': 97,
 'salary': 40231758,
 'height': '6-3 / 1.91',
 'weight': '185 lbs',
 'dob': 'March 14, 1988',
 'country': 'USA',
 'college': 'Davidson',
 'draft_year': 2009,
 'draft_round': 1,
 'draft_peak': 7}
 """

In [8]:
new_player = {'Stephen Curry': {'jersey': 30,
 'team': 'Golden State Warriors',
 'position': 'PG',
 'rating': 97,
 'salary': 40231758,
 'height': '6-3 / 1.91',
 'weight': '185 lbs',
 'dob': 'March 14, 1988',
 'country': 'USA',
 'college': 'Davidson',
 'draft_year': 2009,
 'draft_round': 1,
 'draft_peak': 7}
}
players_data.update(new_player)

### Activity3: Remove the salery value for 'Kevin Durant'

Remove the salary value for the player Kevin Durant from the dictionary players_data.

In [9]:
del players_data['Kevin Durant']['salary']
players_data['Kevin Durant']

{'rating': 96,
 'jersey': '#7',
 'team': 'Brooklyn Nets',
 'position': 'F',
 'b_day': '09/29/88',
 'height': '6-10 / 2.08',
 'weight': '230 lbs. / 104.3 kg.',
 'country': 'USA',
 'draft_year': 2007,
 'draft_round': 1,
 'draft_peak': 2,
 'college': 'Texas',
 'version': 'NBA2k20'}

### Activity 4: Access the keys and values of the dictionary

Create a list named players_names which contains the names of all the players in the dictionary players_data. Create another list named players_details which contains every details of all the players in the dictionary players_data. The details of the players should be in the form of a dictionary.

In [10]:
players_names = list(players_data.keys())
players_details = list(players_data.values())
players_details

[{'rating': 97,
  'jersey': '#23',
  'team': 'Los Angeles Lakers',
  'position': 'F',
  'b_day': '12/30/84',
  'height': '6-9 / 2.06',
  'weight': '250 lbs. / 113.4 kg.',
  'salary': '$37436858',
  'country': 'USA',
  'draft_year': 2003,
  'draft_round': 1,
  'draft_peak': 1,
  'college': nan,
  'version': 'NBA2k20'},
 {'rating': 97,
  'jersey': '#2',
  'team': 'Los Angeles Clippers',
  'position': 'F',
  'b_day': '06/29/91',
  'height': '6-7 / 2.01',
  'weight': '225 lbs. / 102.1 kg.',
  'salary': '$32742000',
  'country': 'USA',
  'draft_year': 2011,
  'draft_round': 1,
  'draft_peak': 15,
  'college': 'San Diego State',
  'version': 'NBA2k20'},
 {'rating': 96,
  'jersey': '#34',
  'team': 'Milwaukee Bucks',
  'position': 'F-G',
  'b_day': '12/06/94',
  'height': '6-11 / 2.11',
  'weight': '242 lbs. / 109.8 kg.',
  'salary': '$25842697',
  'country': 'Greece',
  'draft_year': 2013,
  'draft_round': 1,
  'draft_peak': 15,
  'college': nan,
  'version': 'NBA2k20'},
 {'rating': 96,
  'j

### Activity 5: Find the number of players in the player data dictionary

How many players are there in the dictionary players_data?

In [11]:
len(players_data)

50

### Activity 6: Create a new dictionary players_rating

Create a dictionary named players_rating which contains the names of the players as keys and the rating of the players as values. The dictionary should contain the rating of all the players in the dictionary players_data

In [12]:
players_rating = {}
for player in players_data:
    new_player = {player : players_data[player]['rating']}
    players_rating.update(new_player)


or more efficient:

In [13]:
players_rating = {}
for name, details in players_data.items():
    players_rating[name] = details['rating']

### Activity 7: Check if value is present or not in the dictionary

Check if the 'Joel Embiid' and 'Jimmy' are present in the dictionary players_data

In [14]:
a1 = 'Joel Embiid' in players_data.keys()
a2 = 'Jimmy' in players_data.keys()
print(a1, a2)

True False


### Activity 8: Merge two dictionaroes

Merge the two dictionaries below into players_data_merged

<code>player_stats = {
    'LeBron James': {'rating': 97, 'jersey': '#23', 'team': 'Los Angeles Lakers', 'position': 'F', 'b_day': '12/30/84', 'height': '6-9 / 2.06', 'weight': '250 lbs. / 113.4 kg.', 'country': 'USA', 'draft_year': 2003, 'draft_round': 1, 'draft_peak': 1, 'college': None},
    'Kawhi Leonard': {'rating': 97, 'jersey': '#2', 'team': 'Los Angeles Clippers', 'position': 'F', 'b_day': '06/29/91', 'height': '6-7 / 2.01', 'weight': '225 lbs. / 102.1 kg.', 'country': 'USA', 'draft_year': 2011, 'draft_round': 1, 'draft_peak': 15, 'college': 'San Diego State'},
    'Giannis Antetokounmpo': {'rating': 96, 'jersey': '#34', 'team': 'Milwaukee Bucks', 'position': 'F-G', 'b_day': '12/06/94', 'height': '6-11 / 2.11', 'weight': '242 lbs. / 109.8 kg.', 'country': 'Greece', 'draft_year': 2013, 'draft_round': 1, 'draft_peak': 15, 'college': None},
    'Kevin Durant': {'rating': 96, 'jersey': '#7', 'team': 'Brooklyn Nets', 'position': 'F', 'b_day': '09/29/88', 'height': '6-10 / 2.08', 'weight': '230 lbs. / 104.3 kg.', 'country': 'USA', 'draft_year': 2007, 'draft_round': 1, 'draft_peak': 2, 'college': 'Texas'},
    'James Harden': {'rating': 96, 'jersey': '#13', 'team': 'Houston Rockets', 'position': 'G', 'b_day': '08/26/89', 'height': '6-5 / 1.96', 'weight': '220 lbs. / 99.8 kg.', 'country': 'USA', 'draft_year': 2009, 'draft_round': 1, 'draft_peak': 3, 'college': 'Arizona State'}}
</code>

<code>
player_salaries = {'LeBron James': '$37436858', 'Kawhi Leonard': '$32742000', 'Giannis Antetokounmpo': '$25842697', 'Kevin Durant': '$37199000', 'James Harden': '$38199000'}
</code>

In [15]:
player_stats = {'LeBron James': {'rating': 97, 'jersey': '#23', 'team': 'Los Angeles Lakers', 'position': 'F', 'b_day': '12/30/84', 'height': '6-9 / 2.06', 'weight': '250 lbs. / 113.4 kg.', 'country': 'USA', 'draft_year': 2003, 'draft_round': 1, 'draft_peak': 1, 'college': None},
                'Kawhi Leonard': {'rating': 97, 'jersey': '#2', 'team': 'Los Angeles Clippers', 'position': 'F', 'b_day': '06/29/91', 'height': '6-7 / 2.01', 'weight': '225 lbs. / 102.1 kg.', 'country': 'USA', 'draft_year': 2011, 'draft_round': 1, 'draft_peak': 15, 'college': 'San Diego State'},
                'Giannis Antetokounmpo': {'rating': 96, 'jersey': '#34', 'team': 'Milwaukee Bucks', 'position': 'F-G', 'b_day': '12/06/94', 'height': '6-11 / 2.11', 'weight': '242 lbs. / 109.8 kg.', 'country': 'Greece', 'draft_year': 2013, 'draft_round': 1, 'draft_peak': 15, 'college': None},
                'Kevin Durant': {'rating': 96, 'jersey': '#7', 'team': 'Brooklyn Nets', 'position': 'F', 'b_day': '09/29/88', 'height': '6-10 / 2.08', 'weight': '230 lbs. / 104.3 kg.', 'country': 'USA', 'draft_year': 2007, 'draft_round': 1, 'draft_peak': 2, 'college': 'Texas'},
                'James Harden': {'rating': 96, 'jersey': '#13', 'team': 'Houston Rockets', 'position': 'G', 'b_day': '08/26/89', 'height': '6-5 / 1.96', 'weight': '220 lbs. / 99.8 kg.', 'country': 'USA', 'draft_year': 2009, 'draft_round': 1, 'draft_peak': 3, 'college': 'Arizona State'}}


player_salaries = {'LeBron James': '$37436858', 'Kawhi Leonard': '$32742000', 'Giannis Antetokounmpo': '$25842697', 'Kevin Durant': '$37199000', 'James Harden': '$38199000'}

In [16]:
players_data_merged = {}
for player in player_stats:
    players_data_merged[player] = player_stats[player]
    if player in player_salaries:
        players_data_merged[player]['salary'] = player_salaries[player]


players_data_merged

{'LeBron James': {'rating': 97,
  'jersey': '#23',
  'team': 'Los Angeles Lakers',
  'position': 'F',
  'b_day': '12/30/84',
  'height': '6-9 / 2.06',
  'weight': '250 lbs. / 113.4 kg.',
  'country': 'USA',
  'draft_year': 2003,
  'draft_round': 1,
  'draft_peak': 1,
  'college': None,
  'salary': '$37436858'},
 'Kawhi Leonard': {'rating': 97,
  'jersey': '#2',
  'team': 'Los Angeles Clippers',
  'position': 'F',
  'b_day': '06/29/91',
  'height': '6-7 / 2.01',
  'weight': '225 lbs. / 102.1 kg.',
  'country': 'USA',
  'draft_year': 2011,
  'draft_round': 1,
  'draft_peak': 15,
  'college': 'San Diego State',
  'salary': '$32742000'},
 'Giannis Antetokounmpo': {'rating': 96,
  'jersey': '#34',
  'team': 'Milwaukee Bucks',
  'position': 'F-G',
  'b_day': '12/06/94',
  'height': '6-11 / 2.11',
  'weight': '242 lbs. / 109.8 kg.',
  'country': 'Greece',
  'draft_year': 2013,
  'draft_round': 1,
  'draft_peak': 15,
  'college': None,
  'salary': '$25842697'},
 'Kevin Durant': {'rating': 96,


### Activity 9: Update the values for 'Mike Conley'

Update the rating and salary for 'Mike Conley' in the players_data dictionary to 95 and '$34,000,000' respectively.

In [17]:
players_data['Mike Conley'].update({'rating': 95, 'salary': '$34,000,000'})

### Activity 10: Create a new dictionary with specific country

Create a new dictionary players_data_usa with the players from the USA which contains the player name as the key and list of rating and team as the value.
The result of the players_data_usa should look like this
<code>
{'LeBron James': [97, 'Los Angeles Lakers'],
 'Kawhi Leonard': [97, 'Los Angeles Clippers'],
 'James Harden': [96, 'Houston Rockets'],
 'Kevin Durant': [96, 'Brooklyn Nets'],
...
}
</code>

In [18]:
players_data_usa = {}
for key, values in players_data.items():
    if values['country'] == 'USA':
        players_data_usa[key] = [values['rating'], values['team']]
players_data_usa

{'LeBron James': [97, 'Los Angeles Lakers'],
 'Kawhi Leonard': [97, 'Los Angeles Clippers'],
 'Kevin Durant': [96, 'Brooklyn Nets'],
 'James Harden': [96, 'Houston Rockets'],
 'Stephen Curry': [97, 'Golden State Warriors'],
 'Anthony Davis': [94, 'Los Angeles Lakers'],
 'Paul George': [93, 'Los Angeles Clippers'],
 'Damian Lillard': [92, 'Portland Trail Blazers'],
 'Russell Westbrook': [90, 'Houston Rockets'],
 'Klay Thompson': [89, 'Golden State Warriors'],
 'Karl-Anthony Towns': [89, 'Minnesota Timberwolves'],
 'Jimmy Butler': [88, 'Miami Heat'],
 'Blake Griffin': [88, 'Detroit Pistons'],
 'Donovan Mitchell': [88, 'Utah Jazz'],
 'Kemba Walker': [88, 'Boston Celtics'],
 'LaMarcus Aldridge': [87, 'San Antonio Spurs'],
 'Bradley Beal': [87, 'Washington Wizards'],
 'Mike Conley': [95, 'Utah Jazz'],
 'DeMar DeRozan': [87, 'San Antonio Spurs'],
 'CJ McCollum': [87, 'Portland Trail Blazers'],
 'Victor Oladipo': [87, 'Indiana Pacers'],
 "D'Angelo Russell": [87, 'Minnesota Timberwolves'],
 "D

### Activity 11: Create a new dictionary of teams from players_data

Create a dictionary teams with the unique teams in the players_data dictionary as the key and the number of players in each team as the value.

<code>
{'Los Angeles Lakers': 2,
 'Los Angeles Clippers': 2,
 'Milwaukee Bucks': 3,
 'Brooklyn Nets': 2,
...
}
</code>

In [19]:
teams = {}
for key, values in players_data.items():
    if values['team'] not in teams:
        teams[values['team']] = 1
    else:
        current_team_count = teams[values['team']]
        teams[values['team']] = current_team_count + 1

teams

{'Los Angeles Lakers': 2,
 'Los Angeles Clippers': 2,
 'Milwaukee Bucks': 3,
 'Brooklyn Nets': 2,
 'Houston Rockets': 2,
 'Golden State Warriors': 3,
 'Portland Trail Blazers': 2,
 'Philadelphia 76ers': 4,
 'Denver Nuggets': 1,
 'Minnesota Timberwolves': 2,
 'Miami Heat': 1,
 'Utah Jazz': 3,
 'Detroit Pistons': 1,
 'Boston Celtics': 2,
 'Dallas Mavericks': 2,
 'San Antonio Spurs': 2,
 'Washington Wizards': 2,
 'Indiana Pacers': 1,
 'Toronto Raptors': 2,
 'Sacramento Kings': 1,
 'Phoenix Suns': 1,
 nan: 1,
 'Cleveland Cavaliers': 1,
 'New Orleans Pelicans': 1,
 'Orlando Magic': 1,
 'Atlanta Hawks': 3,
 'Chicago Bulls': 1,
 'Oklahoma City Thunder': 1}

### Activity 13 Copy the dictionary and clear all the elements

Copy the players_data dictionary to a new dictionary players_data_copy and clear all the elements from the players_data dictionary.

In [20]:
players_data_copy = players_data.copy()
players_data.clear()